# STAGE_MODE DEFINITION

uint16 STAGE_INIT                          = 000
uint16 STAGE_INIT_MODE_INIT                = 001
uint16 STAGE_INIT_MODE_REF                 = 002
uint16 STAGE_INIT_MODE_TAKEOFF             = 003

uint16 STAGE_DTC                           = 100
uint16 STAGE_DTC_MODE_RISE                 = 101
uint16 STAGE_DTC_MODE_ADJ                  = 102
uint16 STAGE_DTC_MODE_LOC                  = 103

uint16 STAGE_TRK_1                         = 200
uint16 STAGE_TRK_1_MODE_BLD_1_GO           = 201
uint16 STAGE_TRK_1_MODE_BLD_1_BK           = 202
uint16 STAGE_TRK_1_MODE_BLD_2_GO           = 203
uint16 STAGE_TRK_1_MODE_BLD_2_BK           = 204
uint16 STAGE_TRK_1_MODE_BLD_3_GO           = 205
uint16 STAGE_TRK_1_MODE_BLD_3_BK           = 206

uint16 STAGE_TRK_2                         = 300
uint16 STAGE_TRK_2_MODE_BLD_1_GO           = 301
uint16 STAGE_TRK_2_MODE_BLD_1_TP           = 302
uint16 STAGE_TRK_2_MODE_BLD_1_BK           = 303
uint16 STAGE_TRK_2_MODE_BLD_1_RT           = 304
uint16 STAGE_TRK_2_MODE_BLD_2_GO           = 305
uint16 STAGE_TRK_2_MODE_BLD_2_TP           = 306
uint16 STAGE_TRK_2_MODE_BLD_2_BK           = 307
uint16 STAGE_TRK_2_MODE_BLD_2_RT           = 308
uint16 STAGE_TRK_2_MODE_BLD_3_GO           = 309
uint16 STAGE_TRK_2_MODE_BLD_3_TP           = 310
uint16 STAGE_TRK_2_MODE_BLD_3_BK           = 311
uint16 STAGE_TRK_2_MODE_BLD_3_RT           = 312

uint16 STAGE_TRK_4                         = 400
uint16 STAGE_TRK_4_MODE_BLD_1_S1           = 401
uint16 STAGE_TRK_4_MODE_BLD_1_13           = 402
uint16 STAGE_TRK_4_MODE_BLD_1_S3           = 403
uint16 STAGE_TRK_4_MODE_BLD_1_34           = 404
uint16 STAGE_TRK_4_MODE_BLD_1_S4           = 405
uint16 STAGE_TRK_4_MODE_BLD_1_42           = 406
uint16 STAGE_TRK_4_MODE_BLD_1_S2           = 407
uint16 STAGE_TRK_4_MODE_BLD_1_20           = 408
uint16 STAGE_TRK_4_MODE_BLD_2_S1           = 409
uint16 STAGE_TRK_4_MODE_BLD_2_13           = 410
uint16 STAGE_TRK_4_MODE_BLD_2_S3           = 411
uint16 STAGE_TRK_4_MODE_BLD_2_34           = 412
uint16 STAGE_TRK_4_MODE_BLD_2_S4           = 413
uint16 STAGE_TRK_4_MODE_BLD_2_42           = 414
uint16 STAGE_TRK_4_MODE_BLD_2_S2           = 415
uint16 STAGE_TRK_4_MODE_BLD_2_20           = 416
uint16 STAGE_TRK_4_MODE_BLD_3_S1           = 417
uint16 STAGE_TRK_4_MODE_BLD_3_13           = 418
uint16 STAGE_TRK_4_MODE_BLD_3_S3           = 419
uint16 STAGE_TRK_4_MODE_BLD_3_34           = 420
uint16 STAGE_TRK_4_MODE_BLD_3_S4           = 421
uint16 STAGE_TRK_4_MODE_BLD_3_42           = 422
uint16 STAGE_TRK_4_MODE_BLD_3_S2           = 423
uint16 STAGE_TRK_4_MODE_BLD_3_20           = 424


uint16 STAGE_FNS                           = 500
uint16 STAGE_FNS_MODE_DES                  = 501
uint16 STAGE_FNS_MODE_LAND                 = 502




# msg

uint16 stage_mode 

