source ./devel/setup.bash;
echo " " | sudo -S chmod 777 /dev/ttyUSB0 & sleep 2;
roslaunch realsense2_camera rs_camera.launch & sleep 10;
roslaunch mavros px4.launch & sleep 3;
rosrun mavros mavcmd long 511 31 5000 0 0 0 0 0 & sleep 1;
rosrun mavros mavcmd long 511 105 5000 0 0 0 0 0 & sleep 1;
roslaunch vins fast_drone_250.launch & sleep 1;
roslaunch px4ctrl run_ctrl.launch & sleep 1;
roslaunch ego_planner single_run_in_exp.launch & sleep 1;
roslaunch ego_planner rviz.launch & sleep 1;
wait;
